app = "vocabulary-app-backend"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  SMTP_USERNAME = "dwiputro.rio@gmail.com"
  SMTP_SERVER = "smtp.gmail.com"
  SMTP_PORT = "465"
  SMTP_FROM_EMAIL = "dwiputro.rio@gmail.com"
  PORT = "8080"
  HOST = "0.0.0.0"
  RUST_LOG = "info"
  RUST_BACKTRACE = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "vocabulary_data"
  destination = "/data"

[processes]
  app = "/app/backend"
